---
title: "Violent Crime"
author: "Serena Leung"
date: "12/16/2021"
output: html_document
---

```{r}
library(Synth)
library(tidyverse)
```


Read data 
```{r}
library(readxl)
vio_crime <- read_excel("~/Thesis/Master State Crime.xlsx", 
    sheet = "Violent Crime", skip = 1)
vio_crime
```


```{r}
vio_crime <- pivot_longer(vio_crime, cols = c(-State), names_to = "year", values_to = "rate") %>% 
  transform(ID = as.numeric(factor(State)), year = as.numeric(year))

vio_crime
```



Data prep process for the all 50 states 
```{r}
dataprep.out <- dataprep(vio_crime, 
         time.predictors.prior = 2000:2010,
         special.predictors = list(
         list("rate", 2000:2010, "mean")),
         dependent = "rate", 
         unit.variable = "ID",       
         unit.names.variable = "State", 
         time.variable = "year", 
         treatment.identifier = 5, 
         controls.identifier = c(1:4, 6:52),
         time.optimize.ssr = 2000:2010, # pretreatment period
         time.plot = 2000:2019) # time period to be plotted


synth.out = synth(data.prep.obj = dataprep.out, method = "BFGS")
```




Iterating over pretreatment periods
```{r}
iter_year <- function(year){
  
   dataprep.out <- dataprep(vio_crime, 
         time.predictors.prior = 2000:year,
         special.predictors = list(
          list("rate", 2000:year, "mean")),  # am I supposed to change this?
         dependent = "rate", 
         unit.variable = "ID",       
         unit.names.variable = "State", 
         time.variable = "year", 
         treatment.identifier = 5, 
         controls.identifier = c(1:4, 6:52),
         time.optimize.ssr = 2000:year, # pretreatment period
         time.plot = 2000:2019) # time period to be plotted
   
  synth.out = synth(data.prep.obj = dataprep.out, method = "BFGS")
  
  gaps <- dataprep.out$Y1plot - (dataprep.out$Y0plot %*% synth.out$solution.w)

  gaps <- data.frame("Year"=rownames(gaps), gaps)
  
  return(gaps)
  
  # path.plot(synth.res=synth.out, dataprep.res = dataprep.out, 
  #         Ylab="vio_crimelary rate per 100k people", Xlab="year",
  #         Legend = c(paste("California", year),"Synthetic"),
  #         Legend.position = "bottomleft", tr.intake = 2014.9166)
  # abline(v = 2014.9166, col = "red")
  # rect(xleft=2011,xright = 2014 ,ybottom=0,ytop= 5000, density=10, col = "gray") # Realignment
  
}
```


```{r}
gaps <- dataprep.out$Y1plot - (dataprep.out$Y0plot %*% synth.out$solution.w)

gaps <- data.frame("Year"=rownames(gaps), gaps)


plot(gaps, type="l", lwd = 6, ylim = c(-500, 500))
abline(v = 2014.9166, col = "red")
abline(h = 0, lty = 2)

for (i in seq(2000,2010)) {
  year_gap <- iter_year(i)

  lines(year_gap[,1], year_gap[,2], col ="grey")
}


# for(i in seq(2000,2010)){
#   iter_year(i)
# }
```



Iterate over different states as the treatment group

```{r}
# Create generic function that goes through dataprep, synth.out, and plot 
# for state id 2-51

iter_state <- function(id){   # special cases for id = 1 and 52
  
  if (id == 1) {  
     dataprep.out <- dataprep(vio_crime, 
         time.predictors.prior = 2000:2010,
         special.predictors = list(
          list("rate", 2000:2010, "mean")),
         dependent = "rate", 
         unit.variable = "ID",       
         unit.names.variable = "State", 
         time.variable = "year", 
         treatment.identifier = id, 
         controls.identifier = c((id+1):52),
         time.optimize.ssr = 2000:2010, # pretreatment period
         time.plot = 2000:2019) # time period to be plotted
     
  } else if (id == 52) {
    
     dataprep.out <- dataprep(vio_crime, 
         time.predictors.prior = 2000:2010,
         special.predictors = list(
          list("rate", 2000:2010, "mean")),
         dependent = "rate", 
         unit.variable = "ID",       
         unit.names.variable = "State", 
         time.variable = "year", 
         treatment.identifier = id, 
         controls.identifier = c(1:(id-1)),
         time.optimize.ssr = 2000:2010, # pretreatment period
         time.plot = 2000:2019) # time period to be plotted
     
  } else
     dataprep.out <- dataprep(vio_crime, 
         time.predictors.prior = 2000:2010,
         special.predictors = list(
          list("rate", 2000:2010, "mean")),
         dependent = "rate", 
         unit.variable = "ID",       
         unit.names.variable = "State", 
         time.variable = "year", 
         treatment.identifier = id, 
         controls.identifier = c(1:(id-1), (id+1):52),
         time.optimize.ssr = 2000:2010, # pretreatment period
         time.plot = 2000:2019) # time period to be plotted
  
  synth.out = synth(data.prep.obj = dataprep.out, method = "BFGS")
  
  gaps <- dataprep.out$Y1plot - (dataprep.out$Y0plot %*% synth.out$solution.w)

  gaps <- data.frame("Year"=rownames(gaps), gaps)
  
  return(gaps)
  
  # synth.out = synth(data.prep.obj = dataprep.out, method = "BFGS")
  # 
  # path.plot(synth.res=synth.out, dataprep.res = dataprep.out, 
  #         Ylab="Property Crime rate per 100k people", Xlab="year",
  #         Legend = c(id,"Synthetic"),
  #         Legend.position = "bottomleft", tr.intake = 2014.9166)
  # abline(v = 2014.9166, col = "red")
  # rect(xleft=2011,xright = 2014 ,ybottom=0,ytop= 5000, density=10, col = "gray") # Realignment
}

```




```{r}
gaps <- dataprep.out$Y1plot - (dataprep.out$Y0plot %*% synth.out$solution.w)

gaps<- data.frame("Year"=rownames(gaps), gaps)


plot(gaps, type="l", col = "blue", lwd = 2, ylim = c(-500, 500), Ylab = "Gap in Burglary rate per 100k people")

abline(v = 2014.9166, col = "red")
abline(h = 0, lty = 2)

for (id in seq(1,52)) {
  state_gap <- iter_state(id)

  lines(state_gap[,1], state_gap[,2], col ="grey")
}


# for (id in seq(1,52)) {
#   iter_state(id)
# }

```





//////////////////////////////////////////////////////// SC WITH NO RAISE STATES //////////////////////////////////////////////////

```{r}
library(readxl)
NR_vio_crime <- read_excel("~/Thesis/No Raise Master State Crime.xlsx", 
    sheet = "Violent Crime (NR)", skip = 1)

NR_vio_crime = rename(NR_vio_crime, State = "No Raise States")

head(NR_vio_crime)

```



```{r}
NR_vio_crime <- pivot_longer(NR_vio_crime, cols = c(-State), names_to = "year", values_to = "rate") %>%
  transform(ID = as.numeric(factor(State)), year = as.numeric(year))

NR_vio_crime

```



```{r}
dataprep.nr <- dataprep(NR_vio_crime, 
         time.predictors.prior = 2000:2010,
         special.predictors = list(
         list("rate", 2000:2010, "mean")),
         dependent = "rate", 
         unit.variable = "ID",       
         unit.names.variable = "State", 
         time.variable = "year", 
         treatment.identifier = 1, 
         controls.identifier = c(2:14),
         time.optimize.ssr = 2000:2010, # pretreatment period
         time.plot = 2000:2019) # time period to be plotted
```


```{r}
synth.nr = synth(data.prep.obj = dataprep.nr, method = "BFGS")
```



Iterating through the No Raise States 
```{r}
gaps <- dataprep.nr$Y1plot - (dataprep.nr$Y0plot %*% synth.nr$solution.w)

gaps<- data.frame("Year"=rownames(gaps), gaps)



plot(gaps, type="l", col = "blue", lwd = 2, ylim = c(-500, 500), Ylab = "Gap in vio_crimelary Crime rate per 100k people")

abline(v = 2014.9166, col = "red")
abline(h = 0, lty = 2)

for (id in seq(1,14)) {
  state_gap <- iter_state(id)

  lines(state_gap[,1], state_gap[,2], col ="grey")
}
```
